[package]
name = "aalto2"
version = "0.1.0"
edition = "2021"
maintainers = ["Elias Arno Eskelinen <elias.eskelinen@pm.me>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"